ConVar g_pConvarCoopEnabled;
ConVar g_pConvarWaitPeriod;

Handle g_pPickupObject;
Handle g_pSendWeaponAnim;

Handle hkFAllowFlashlight;
//Handle hkIsDeathmatch;
Handle hkIRelationType;
Handle hkProtoSniperSelectSchedule;
Handle hkFindNamedEntity;
Handle hkFindNamedEntityClosest;
Handle hkSetModel;
Handle hkAcceptInput;
Handle hkSetSuitUpdate;

CGlobalLevelLump g_pLevelLump;
CCoopSpawn g_SpawnSystem;

char g_szMapName[MAX_MAPNAME];
