#if defined _srccoop_api_util_included
 #endinput
#endif
#define _srccoop_api_util_included

#pragma newdecls required
#pragma semicolon 1

#include <srccoop_api/util/common/assert>
#include <srccoop_api/util/common/array>
#include <srccoop_api/util/common/rgba>
#include <srccoop_api/util/common/entity>
#include <srccoop_api/util/common/file>
#include <srccoop_api/util/common/gamedata>
#include <srccoop_api/util/common/math>
#include <srccoop_api/util/common/memory>
#include <srccoop_api/util/common/player>
#include <srccoop_api/util/common/string>
#include <srccoop_api/util/common/stringbuilder>
#if defined _dhooks_included
#include <srccoop_api/util/common/dhooks>
#endif
#if defined _regex_included
#include <srccoop_api/util/common/regex>
#endif