#pragma newdecls required
#pragma semicolon 1

// ToDo: This is not an enum. Look this up at runtime.

enum AmmoType_t
{
	AMMO_INVALID = 0,
	AMMO_9MM = 1,
	AMMO_357 = 2,
	AMMO_BOLTS = 3,
	AMMO_SHELLS = 4,
	AMMO_ENERGY = 5,
	AMMO_MP5NADE = 6,
	AMMO_ROCKETS = 7,
	AMMO_NADES = 8,
	AMMO_SATCHELS = 9,
	AMMO_TRIPMINES = 10,
	AMMO_HIVEGUN = 11,
	AMMO_SNARKS = 12,
	// non-equippable ammo types:
	AMMO_50CAL = 13,
	AMMO_SENTRY = 14,
	AMMO_SNIPERROUND = 15,
	AMMO_SNIPERPENETRATEDROUND = 16
}
